baseURL = "https://www.alexflom.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Top of Mind"

# theme as hugo module
theme = "github.com/lxndrblz/anatole"
# theme as git submodule
#theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-M3995ZTREG"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false